# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T19:03:32+00:00



import argparse
import json
import os
from typing import *
from typing import Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity

from models import BinIdGetResponse, CreateStatus, DeleteStatus, Error, UpdateStatus

app = MCPProxy(
    description='JSON storage API',
    title='JSON storage',
    version='0.1',
    servers=[{'url': 'https://extendsclass.com/api/json-storage'}],
)


@app.post('/bin', tags=['json_bin_management'])
def post_bin():
    """
    Create a json bin
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/bin/{id}', tags=['json_bin_management'])
def delete_bin__id(id: str):
    """
    Delete a json bin
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/bin/{id}', tags=['json_bin_management'])
def get_bin__id(id: str):
    """
    Return a json bin
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch('/bin/{id}', tags=['json_bin_management'])
def patch_bin__id(id: str):
    """
    Partially update a json bin with JSON Merge Patch
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put('/bin/{id}', tags=['json_bin_management'])
def put_bin__id(id: str):
    """
    Update a json bin
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
