# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T19:03:32+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class CreateStatus(BaseModel):
    id: Optional[str] = Field(None, title='Id of the bin')
    status: Optional[int] = Field(None, title='Update status (0: Success)')
    uri: Optional[str] = Field(None, title='URI of the bin')


class DeleteStatus(BaseModel):
    status: Optional[int] = Field(None, title='Update status (0: Success)')


class Error(BaseModel):
    message: Optional[str] = Field(None, title='Error message')
    status: Optional[int] = Field(None, title='Status (1: Error)')


class UpdateStatus(BaseModel):
    data: Optional[Dict[str, Any]] = Field(None, title='Data updated')
    status: Optional[int] = Field(None, title='Update status (0: Success)')


class BinIdGetResponse(BaseModel):
    pass
